apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:Sl9BTC4/fw4j7GOcLpEWirgAhfbQW0hSLSb1vHTM5PR3T79lgXKwNA==,iv:JOvfJm546V9rys6rcY+owju3pNDETYv+mH8tU2s1R+o=,tag:enlQ3epKkElrwTsrJliX5w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qan480dt2yx04pc5g96paq9k8ctcmk3f8rzxv8mx9ydc8twwefrqw888fq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3UzNNaXhvaUZNd1NGQ1VE
            N2RRNmpVSzZ0N2ZEV2Q2TE1FdlM3ajRDK1JrCkExVFFha2pwaXBQVjk4Vy9HRHBZ
            N1BPS2lrS1QrUmdqem1SNnY4N0Y0WFkKLS0tIHI1MnZ2SURUdk5yYlFHUHV4MVdJ
            cEt0a1haWUcvZ1VSaU5xM2ZjVjdscEEKYaa1BbmpaIkALVpYj8QMvu5BpGCOKkKz
            MfFsyQfxDti2nXwCcsWY9qjk4uGen6vAZVGvl0BCnYs7PIfAlZEeBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:30:41Z"
    mac: ENC[AES256_GCM,data:OLda9PjybpfQ9GqFEEumGmiCgDCFqCtxU9C+ZBXUjwMgQLUgMSxrj7m68RIVGmA39bNRulSnQ7Qd5mKbfTaU4Kvr1bJwvHcPDVYQFD0nxZEda0KcVDsTaBpJLZZ8/d4UXjOXRN5CETFVAC7gVwxxGsRftobkP61lWBhClT+fmOo=,iv:zoEOSXASnlUG3/UlPUMeJ/PGKsbi24S9x3ZNPPfh6lQ=,tag:reDh5+KkbpRususO5K3zQQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
