apiVersion: v1
kind: Secret
metadata:
    name: external-dns-secret
    namespace: networking
stringData:
    api-token: ENC[AES256_GCM,data:ILKprrQ+oGvy4phK3bfddM4ci/yldR7Mc4QI/hNnFS5KXH0cpspxbg==,iv:u0Uo7QJoK5DifpfD+KXzQrIqos3y1P1TFtlhrTpGcSs=,tag:QjrfyssD+wNQl+a1JNm/IQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qan480dt2yx04pc5g96paq9k8ctcmk3f8rzxv8mx9ydc8twwefrqw888fq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXaDNvdm5OSTJ1aGRPOEp0
            Q1pvNGJnR0VDN0dQemtEMmJ2czh0ZmtmSVZjCjAvTTFHRDcvUXhBRjhsMGVkaXc4
            UlJJOTJmV3E2T3c5eHB3a2NEUFhEMjAKLS0tIG53Wml5Z2lya05mdmZzU2V5eGFG
            OEp2UXl6TU5sL3h1QUNTVWY5VGx4SmcKtr39OPCz77rzP/uNXloyuVdr9b6QbJw5
            JseQlqecxVRHUULUHCgFgtQVvykfi535Hcwm3xhIM+LD6Ui5yn2WeQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-12T16:08:44Z"
    mac: ENC[AES256_GCM,data:/u24SMHdxfTzp8DzrRYp6fgGvLsrL+1cerTqO0+7k8eKZExZPnlc3exQbemzSQfQdQBwcCb6Zjzpf5/P3oJNEY6PMBhtRw5uUU4dBjpx69OK8cxulZJMlDRqXjf7ZFA2lMLNZwmLe9WvZA5HXxnUR0sTK/GQ+JO6Iw6HhMwEMiw=,iv:IP80reJX5ZWCmqGs+WDkSQMU/d7yRgyRrswZky2fNik=,tag:7vTpw1ArwSXvpCLaScUXqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
