apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_ACME_EMAIL: ENC[AES256_GCM,data:qSlblMWLx/U+goikJz5hwJbZizzGKizXmnm6+Q==,iv:1DFUXgI8nOCFEZGMpUM1iWFBDyRG3+yJoNCq7j3UWx8=,tag:hixga2inPqPFZoILH0dNfQ==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:REwHlg2BL4jl5HmT3GnIw8fdrAaqG+ecqpv+F4SWxwcGaoAi,iv:IEaS3KbsHCVboeEJpn6++3dZF7E+3dpYFjKIFByshsk=,tag:f809DByCuGAkAIENTgb/8w==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:Ma+xsVgPZlaVe+HHtA==,iv:8EHGhsvPf16KzJww5TFGpxac1CU/ZzskCv8dgGj03O4=,tag:hHzeQqnsXGFwtIpVtwZ9uA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1qan480dt2yx04pc5g96paq9k8ctcmk3f8rzxv8mx9ydc8twwefrqw888fq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1V1JaVThFbmJ0VmJ6YXd0
            Uk5NRm1iT0ZWWUMxTUE3engrQVpKc1JmY21FCjIxNGNPeWYycjlLKzZGZUIzSnhP
            dmY5a2NUNUY2Nk1keVNQK1BmZnFlNjAKLS0tIHk1K1lseWxvejM0cFlSc2wvOGI2
            VENVTWVaZVkrMnc4UUxNenRWYkNIUVkKKXT3ynCCiR6Fg7PeLWbp/DNMKRsZdwxj
            bLlipY0BcrmgIfRNp8rE//mHu0WifyDXu9SvVkSnKwtul6kdaaPtxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T20:30:40Z"
    mac: ENC[AES256_GCM,data:r5nxPtHVzFz4cHYwH6FJyYV/er8ckbjRwvazUhzLYMUXk0V6KjAqnMR5rIPfkI8eYe4TS/03FrEdk/EEjxQhgYFGpBRBAVCcZEZAU+ORrmgZpgaBiIrNzbjmqSdoB8YdXkzZq60J/DmHAd8XhbtbeCoHcSbUp5f5j2o/9rEJTic=,iv:6BQUNkt+3gZVa4cFQBE1Og0Ns+InuA0zdtLkMPgciJ0=,tag:WqabXD8Eno43Az1WZY62hw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
